variables:
  - group: GitHub
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-20.04"

stages:
  - stage: build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"

          - pwsh: npm install
            displayName: "npm install"

          - pwsh: npm run build
            displayName: "npm build"

          - pwsh: ./scripts/make-manifest.ps1
            displayName: "Make manifest"

          - publish: $(Build.SourcesDirectory)/artifacts/manifest.zip
            displayName: "Publish manifest"
            artifact: Manifest

          - bash: |
              git config --global user.email 'bot@airelogic.com'
              git config --global user.name 'GitHub Pages Deploy Bot'
            displayName: Configure git
            condition: and(succeeded(), eq(variables.isMain, true))

          - pwsh: npm run deploy -- -r https://$(GITHUB_WRITE_TOKEN)@github.com/airelogic/teams-app-demo.git
            displayName: "Deploy to GitHub Pages"
            condition: and(succeeded(), eq(variables.isMain, true))
